const categoryRoute = require('../routes/categroyRoutes')
const subCategoryRoute = require('../routes/subCategoryRoutes')
const brandRoute = require('../routes/brandRoutes')
const productRoute = require('../routes/productRoutes')
const userRoute = require('../routes/userRoutes')
const authRoute = require('../routes/authRoutes')
const reviewRoute = require('../routes/reviewRoutes')
const wishlistRoute = require('../routes/whishlistRoutes')
const addressRoute = require('../routes/addressRoute')
const couponRoute = require('../routes/couponRoute')
const cartRoute = require('../routes/cartRoutes')
const orderRoute = require('../routes/orderRoute')
const mountRoutes = (app) => {
    app.use('/api/v1/category', categoryRoute)
    app.use('/api/v1/subCategory', subCategoryRoute)
    app.use('/api/v1/brand', brandRoute)
    app.use('/api/v1/product', productRoute)
    app.use('/api/v1/user', userRoute)
    app.use('/api/v1/auth', authRoute)
    app.use('/api/v1/review', reviewRoute)
    app.use('/api/v1/wishlist', wishlistRoute)
    app.use('/api/v1/address', addressRoute)
    app.use('/api/v1/coupon', couponRoute)
    app.use('/api/v1/cart', cartRoute)
    app.use('/api/v1/orders', orderRoute)
}
module.exports = mountRoutes
